---
plugin-name: essentalsTp+
sqlite-dbname: essentials_tp
tpa-here-cooldown: "30"
tp-home-cooldown: "5"
tp-warp-cooldown: "5"
tp-spawn-cooldown: "5"
MOTD: 欢迎来到这个棒棒的插件展示第一天的地狱LOLOLOLOLOL
wild-MaxX: "300"
wild-MaxY: "300"
bed-sets-home: "true"
Lang_invalid_usage: 'INVALID USAGE:'
Lang_command_only_use_ingame: 这个指令只能在游戏中使用.
Lang_no_permissions: '[EssentialsTP] No permission.'
Lang_teleport_home: 传送你到家.
Lang_teleport_spawn: 传送你到出生点.
Lang_teleport_wild: 传送你到随机位置.
Lang_teleport_death: 传送你到上次死亡点.
Lang_no_spawn_set: 没有设置这个世界的重生点···传送你到默认重生点.
Lang_teleport_spawn_original: 传送你到世界默认重生点.
Lang_spawn_set: 出生点设置.
Lang_your_homes: 'Your home:'
Lang_no_home_set: 你还没有设置这个家.
Lang_no_home_name: 你没有这个家的名字.
Lang_home_set: 家设置
Lang_home_delete_1: 'Home named:'
Lang_home_delete_2: 已经被删除.
Lang_no_teleport_self: 你不能传送到你自己的地方.
Lang_player_not_online: 此玩家不在线.
Lang_sent_request_you: 向你发送找人请求.
Lang_sent_request_them: 邀请你传送到TA的位置.
Lang_accept_request: 来接收这个请求.
Lang_decline_request: 来拒绝这个请求.
Lang_request_expire_1: 这个请求还剩
Lang_request_expire_2: 秒
Lang_request_expire_3: 过期.
Lang_type: Type
Lang_no_active_request: 没有请求存在.
Lang_warps: 'Warps:'
Lang_no_warps: 这个服务器没有传送点.
Lang_no_warp_listed: 没有该名称的传送点.
Lang_warp_set: 传送点设置
Lang_warp_to: 你传送到
Lang_warp_delete_1: 'Warp named:'
Lang_warp_delete_2: 已经被删除.
Lang_no_warps_name: 没有与该服务器匹配的传送点.
Land_chunk_not_loaded: 没有加载区块.
Lang_action_cooldown: 这个动作还在冷却.
Lang_no_death: 请再死亡一次.
...
